# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tim Stuart
tagline:
paginate:         1
baseurl:          /
author:
  name:           Tim Stuart
  email:          timstuart90@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/timoast

pages_list:
  About: '/about'
  Archive: '/archive'
  Code: '/code'
  Publications: '/publications'
  Feed: '/atom.xml'
